global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "yape-gateway-backend-metrics"
    metrics_path: /metrics
  #  scheme: https #Use in https server deploys
    static_configs:
      - targets: ['host.docker.internal:3002']